#!/usr/bin/env python3
"""Bundle the daemon package into a single self-contained ``dist/daemon.py``.

DM1 form: zero code moves yet. The "package" is one file (``daemon.py``);
the bundler prepends an auto-generated header + writes the result. This
exists to validate the publish pipeline BEFORE any extraction (DM3-DM7)
moves code around.

DM3 onward this script learns to walk a real package layout and concat
modules in dependency order. The header contract — git rev + timestamp
marker — stays the same so the bundled artifact remains traceable to
source for every release."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "daemon.py"
DIST = ROOT / "dist"
OUT = DIST / "daemon.py"


def _git_rev() -> str:
    """Short HEAD sha, or 'untracked' outside a git tree (CI / detached)."""
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "untracked"


def _header(rev: str) -> str:
    return (
        "#!/usr/bin/env python3\n"
        "# AUTO-GENERATED by daemon/bundle.py — do not edit this file.\n"
        "# Edit daemon/daemon.py (or, post-DM3, the source modules under daemon/)\n"
        "# then re-run `python daemon/bundle.py`.\n"
        f"# Source: {rev}\n"
    )


def bundle() -> Path:
    """Write the bundled artifact + a tls/ symlink alongside it. Strips
    the source file's own shebang (if any) so we don't end up with two.
    The tls/ link mirrors the production layout — the daemon's
    ``_find_tls_bundle()`` looks for ``<here>/tls/`` next to its own
    ``__file__``; the publisher in DM6 must copy (not link) for the
    public CDN."""
    DIST.mkdir(parents=True, exist_ok=True)
    body = SRC.read_text()
    if body.startswith("#!"):
        body = body.split("\n", 1)[1]
    OUT.write_text(_header(_git_rev()) + body)
    OUT.chmod(0o755)
    tls_link = DIST / "tls"
    if not tls_link.exists():
        tls_link.symlink_to(ROOT / "tls", target_is_directory=True)
    return OUT


if __name__ == "__main__":
    out = bundle()
    print(f"wrote {out} ({out.stat().st_size:,} bytes)", file=sys.stderr)
