#!/usr/bin/env python3
"""Bundle the daemon package into a single self-contained ``dist/daemon.py``.

DM3+ form: walks the source modules in dependency order, strips the
sibling-module imports (each module's body becomes part of one big
file's global namespace, so the cross-module names resolve naturally),
prepends an auto-generated header, writes ``dist/daemon.py``.

Dependency order (top of bundle → bottom):

    paths.py    — Paths + TLS constants. No sibling deps.
    storage.py  — ChatArchive, StorageReport, UploadStore,
                  ChatQueueManager. Depends on paths.
    daemon.py   — wiring + main + everything else. Depends on both.

Shadowing rule: when paths.py / storage.py and daemon.py both define
the same name (notably ``_log`` / ``_iso_now`` — storage.py keeps
local copies for source-tree dev; daemon.py has the full
debug-stream-aware versions), the LATER definition wins in Python
module namespace. Bundle ordering must keep daemon.py last so
production gets the canonical helpers."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "daemon.py"
DIST = ROOT / "dist"
OUT = DIST / "daemon.py"

# Sibling modules to inline ahead of daemon.py, in dep order.
MODULES = [
    "paths.py",
    "utils.py",
    "hub.py",
    "registries.py",
    "render.py",
    "runs.py",
    "storage.py",
    "chat.py",
    "agent_prompts.py",
    "prompts.py",
    "runner.py",
    "quota.py",
    "routes.py",
]

# Lines of the form ``from <mod> import …`` where <mod> is one of our
# sibling modules. Stripped from each file so the bundle's flat global
# namespace doesn't trip over missing modules. ``from daemon import …``
# is stripped too: there is no ``daemon`` module inside the single-file
# bundle, so any such line (an extracted sibling reaching back for a
# daemon-defined constant like ``DAEMON_VERSION`` at runtime) MUST be
# dropped — the name resolves via the bundle's flat global namespace.
SIBLING_PREFIXES = tuple(f"from {m[:-3]} import " for m in MODULES) + (
    "from daemon import ",
)


def _git_rev() -> str:
    """Short HEAD sha, or 'untracked' outside a git tree (CI / detached)."""
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "untracked"


def _header(rev: str) -> str:
    return (
        "#!/usr/bin/env python3\n"
        "# AUTO-GENERATED by daemon/bundle.py — do not edit this file.\n"
        "# Edit daemon/daemon.py (or, post-DM3, the source modules under daemon/)\n"
        "# then re-run `python daemon/bundle.py`.\n"
        f"# Source: {rev}\n"
    )


def _strip_sibling_imports(text: str) -> str:
    """Drop sibling-module import lines + duplicate ``from __future__``
    lines. Python's __future__ imports must appear at the very top of
    a file; the bundle puts one canonical line at the very top and
    every inlined module's local copy is stripped.

    Handles the multi-line form ``from <sibling> import (\\n  A,\\n  B,\\n)``:
    when the drop-prefix line ends with ``(``, every subsequent line is
    dropped until the matching ``)``."""
    drop_prefixes = SIBLING_PREFIXES + ("from __future__ import ",)
    keep: list[str] = []
    skip_until_close = False
    for line in text.splitlines(keepends=True):
        if skip_until_close:
            if ")" in line:
                skip_until_close = False
            continue
        if line.lstrip().startswith(drop_prefixes):
            # If this opens a multi-line `from X import (` (has `(` but no
            # matching `)` on the same line, ignoring trailing comments),
            # skip continuation lines until we see the closing `)`.
            if "(" in line and ")" not in line.split("#", 1)[0]:
                skip_until_close = True
            continue
        keep.append(line)
    return "".join(keep)


def _strip_shebang(text: str) -> str:
    """Drop the leading ``#!...`` line if present so the bundle has
    exactly one (the header's)."""
    if text.startswith("#!"):
        return text.split("\n", 1)[1]
    return text


def bundle() -> Path:
    """Write the bundled artifact + a tls/ symlink alongside it.

    Order: header → each sibling module (paths, storage, …) → daemon.py.
    Each part is sibling-import-stripped. The tls/ link mirrors the
    production layout — the daemon's ``_find_tls_bundle()`` looks for
    ``<here>/tls/`` next to its own ``__file__``; the publisher in DM6
    must copy (not link) for the public CDN."""
    DIST.mkdir(parents=True, exist_ok=True)
    parts = [
        _header(_git_rev()),
        "from __future__ import annotations\n\n",
    ]
    for mod in MODULES:
        body = (ROOT / mod).read_text()
        parts.append(
            f"\n\n# ── inlined from daemon/{mod} (DM3+ bundle) ─────────────────────────\n"
        )
        parts.append(_strip_sibling_imports(_strip_shebang(body)))
    parts.append(
        "\n\n# ── inlined from daemon/daemon.py — main module ──────────────────────\n"
    )
    parts.append(_strip_sibling_imports(_strip_shebang(SRC.read_text())))
    OUT.write_text("".join(parts))
    OUT.chmod(0o755)
    tls_link = DIST / "tls"
    if not tls_link.exists():
        tls_link.symlink_to(ROOT / "tls", target_is_directory=True)
    return OUT


if __name__ == "__main__":
    out = bundle()
    print(f"wrote {out} ({out.stat().st_size:,} bytes)", file=sys.stderr)
