"""scaffold.py — `daemon.py init`: authoritative first-boot scaffolding.

Why this exists (py-1.27.0). Before this module, a brand-new cluster was
scaffolded entirely by a "paste this in your coding agent" prompt
generated by the Architect frontend (genPrompt.ts). That prompt hand-wrote
cluster.yaml, the folder layout, the .gitignore and the starter task
against the standard schema — and it drifted: it was pinned to
STANDARD_VERSION=7 while the live standard was v26, slugged ids wrong,
broke on names with spaces, and stopped to ask the operator questions.
A coding agent following it produced divergences and alerts instead of a
clean cluster.

The fix: the DAEMON owns scaffolding. The daemon ships matching the
standard version it targets, so the files it writes are correct by
construction — no drift class possible. In the centralized model the
already-running machine daemon adopts a new project (`POST /projects
{path}`) and runs this scaffolding for it when the target has no
cluster.yaml yet — the project never gets daemon code of its own.

`scaffold_cluster()` is idempotent-safe: it REFUSES to clobber an
existing cluster.yaml (the `--force` flag in daemon.py overrides). It is
self-contained — only `Paths` + stdlib + two best-effort HTTP fetches
(canonical preamble + live standard version), each with an offline
fallback so `init` always completes.

Layout written (Standard v26 §2 folder_layout, git contract = commit
public/docs/modules/roadmap, gitignore runtime/credentials/timeline/log):

    .meshkore/STANDARD_VERSION
    .meshkore/public/cluster.yaml
    .meshkore/public/README.md
    .meshkore/public/AGENT_INSTRUCTIONS.md   (+ rendered CLAUDE/AGENTS/GEMINI/…)
    .meshkore/docs/governance.md
    .meshkore/docs/INDEX.md
    .meshkore/modules/{general,project}/README.md  (+ tasks/ log/)
    .meshkore/modules/general/tasks/T1-hello.md
    .meshkore/roadmap/initiatives/
    .meshkore/{log,timeline,credentials(0700),scripts/tls}/
    .gitignore   (repo root)
"""

from __future__ import annotations

# NB: aliased to a unique name on purpose. In the single-file bundle the
# flat namespace rebinds bare `datetime` to the CLASS (sibling modules do
# `from datetime import datetime`), so `datetime.date` would resolve to a
# method descriptor and explode. A unique alias is collision-proof.
import datetime as _dtmod
import os
import re
import urllib.request
from pathlib import Path
from typing import Optional

from constants import PORT_RANGE
from paths import Paths
from utils import _log

# The standard version this daemon build targets. Used only as the
# OFFLINE fallback — `init` prefers the live published version so a fresh
# cluster is always born at the current standard, never frozen behind.
DEFAULT_STANDARD_VERSION = 26

_PREAMBLE_URL = "https://api.meshkore.com/v1/standard/agent-instructions.md"
_VERSION_URL = "https://api.meshkore.com/v1/standard/version"
_FETCH_TIMEOUT = 8

# §17 per-CLI render targets (mirror of render._TARGETS). Kept in sync by
# the daemon's boot render anyway — this inline copy just means the files
# exist the instant `init` finishes, before the daemon is even launched.
_CLI_TARGETS = (
    ("CLAUDE.md", "Claude Code (Anthropic)."),
    ("AGENTS.md", "Codex / Aider / general convention."),
    ("GEMINI.md", "Gemini CLI (Google)."),
    (".cursor/rules/meshkore.mdc", "Cursor (Anysphere)."),
    (".clinerules", "Cline (VSCode extension)."),
)

_PREAMBLE_BEGIN = (
    "<!-- MESHKORE_PREAMBLE_BEGIN — managed by the daemon, do not hand-edit -->"
)
_PREAMBLE_END = "<!-- MESHKORE_PREAMBLE_END -->"
_OPERATOR_BEGIN = "<!-- OPERATOR_CONTENT_BEGIN — this is your project. Edit freely. -->"
_OPERATOR_END = "<!-- OPERATOR_CONTENT_END -->"


class ScaffoldError(Exception):
    """Raised when init cannot proceed (e.g. cluster.yaml exists, no --force)."""


def slugify_id(name: str) -> str:
    """Map a display name to a cluster/module id matching the schema
    pattern ``^[a-z0-9-]{2,40}$``. Lowercases, replaces every run of
    non-[a-z0-9] with a single ``-``, trims leading/trailing ``-``,
    clamps to 40, and guarantees ≥2 chars (falls back to ``cluster``)."""
    s = re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")
    s = s[:40].strip("-")
    if len(s) < 2:
        s = "cluster"
    return s


def _preferred_port(slug: str) -> int:
    """Stable hash-derived port in PORT_RANGE for the informational
    transport.endpoint URI. The daemon binds the first FREE port at boot;
    the cockpit identifies the cluster by cluster_id, not by port. This
    only needs to be a valid, plausible URI."""
    lo, hi = PORT_RANGE
    span = hi - lo + 1
    h = 0
    for ch in slug:
        h = (h * 31 + ord(ch)) & 0xFFFFFFFF
    return lo + (h % span)


def _offline() -> bool:
    """Skip the best-effort network fetches (live standard version +
    canonical preamble) and use the offline fallbacks immediately. Honours
    `MESHKORE_OFFLINE` (air-gapped first boot — don't hang ~16s on two
    failing fetches) and `MESHKORE_DAEMON_NO_BOOT_UPDATE` (the hermetic
    flag the test suite already sets, so `init`/auto-scaffold are
    deterministic + network-free under pytest)."""
    return bool(
        os.environ.get("MESHKORE_OFFLINE")
        or os.environ.get("MESHKORE_DAEMON_NO_BOOT_UPDATE")
    )


def _fetch(url: str) -> Optional[str]:
    if _offline():
        return None
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "meshcore-py init"})
        with urllib.request.urlopen(req, timeout=_FETCH_TIMEOUT) as r:
            return r.read().decode("utf-8", errors="replace")
    except Exception as e:
        _log(f"init: fetch {url} failed ({e}) — using offline fallback")
        return None


def _live_standard_version() -> int:
    txt = _fetch(_VERSION_URL)
    if txt:
        try:
            return int(txt.strip()[:8])
        except ValueError:
            pass
    return DEFAULT_STANDARD_VERSION


def _fallback_preamble() -> str:
    """Minimal preamble used only when the canonical fetch fails offline.
    Carries the markers so the daemon's renderer heals it to the full
    canonical text on its first VersionWatcher tick."""
    return (
        "# MeshKore — agent instructions (canonical preamble)\n\n"
        "> This is a placeholder. The daemon will replace this block with the\n"
        "> canonical preamble from <https://meshkore.com/standard> on its next\n"
        "> refresh tick. Until then: this project follows the MeshKore standard\n"
        "> (<https://meshkore.com/standard>). Read `.meshkore/public/RESOURCES.md`\n"
        "> and the standard before doing substantial work in this repo.\n"
    )


def _yaml_str(s: str) -> str:
    """Quote a scalar for our tiny YAML subset — double-quote and escape
    embedded quotes/backslashes so names like `O'Brien "X"` survive."""
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def _w(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text)


def scaffold_cluster(
    root: Path,
    name: str,
    description: Optional[str] = None,
    *,
    cluster_id: Optional[str] = None,
    force: bool = False,
) -> Paths:
    """Write the full v26 .meshkore tree under `root`. Returns the Paths.

    Refuses (ScaffoldError) if cluster.yaml already exists unless force.
    Self-contained: completes even with no network (offline fallbacks)."""
    paths = Paths(root)
    name = (name or "").strip() or "My MeshKore Project"
    slug = slugify_id(cluster_id or name)
    desc = (description or "").strip() or f"Local-first MeshKore cluster — {name}."

    if paths.cluster_yaml.exists() and not force:
        raise ScaffoldError(
            f"cluster.yaml already exists at {paths.cluster_yaml} — refusing to "
            "overwrite. Re-run with `--force` to re-scaffold (destructive)."
        )

    std_ver = _live_standard_version()
    today = _dtmod.date.today().isoformat()
    port = _preferred_port(slug)

    # ── directories (Standard v26 folder_layout) ───────────────────────
    for d in (
        paths.public,
        paths.docs_dir,
        paths.modules_dir / "general" / "tasks",
        paths.modules_dir / "general" / "log",
        paths.modules_dir / "project" / "tasks",
        paths.modules_dir / "project" / "log",
        paths.initiatives,
        paths.log_dir,
        paths.timeline_dir,
        paths.scripts_dir / "tls",
    ):
        d.mkdir(parents=True, exist_ok=True)
    paths.credentials.mkdir(parents=True, exist_ok=True)
    try:
        paths.credentials.chmod(0o700)
    except OSError:
        pass

    # ── STANDARD_VERSION ────────────────────────────────────────────────
    _w(paths.meshkore / "STANDARD_VERSION", str(std_ver))

    # ── public/cluster.yaml (schema 'cluster_yaml', required + sensible) ─
    cluster_yaml = (
        f"# MeshKore cluster config — Standard v{std_ver} (schema 'cluster_yaml').\n"
        f"# Written by `daemon.py init`. Canonical schema:\n"
        f"#   https://api.meshkore.com/v1/standard.json\n"
        f"version: 1\n"
        f"id: {slug}\n"
        f"type: dev\n"
        f"name: {_yaml_str(name)}\n"
        f"description: {_yaml_str(desc)}\n"
        f"\n"
        f"transport:\n"
        f"  protocol: websocket\n"
        f"  # Informational only. The cockpit reads the live endpoint from\n"
        f"  # /health.endpoint and identifies this cluster by `id`, NOT by port.\n"
        f"  # The daemon picks a port in {PORT_RANGE[0]}-{PORT_RANGE[1]} on first boot\n"
        f"  # and STICKS to it (~/.meshkore/ports.json, py-1.15.0+) — it should stay\n"
        f"  # stable across restarts. If external integrations hardcode this port,\n"
        f"  # a drift here breaks them (2026-07-08 incident) — set `architect.port`\n"
        f"  # below to make the assignment durable even if the registry is wiped.\n"
        f'  endpoint: "https://daemon.meshkore.com:{port}"\n'
        f"\n"
        f"storage:\n"
        f"  mode: local\n"
        f"\n"
        f"# Durable seed for _pick_port's sticky registry — only consulted on a\n"
        f"# from-scratch assignment (registry wiped, or first boot on a new\n"
        f"# machine); an existing sticky entry always wins. Safe to bump if you\n"
        f"# deliberately want to move this cluster's daemon to a new port, but\n"
        f"# check for hardcoded consumers first.\n"
        f"architect:\n"
        f"  port: {port}\n"
        f"\n"
        f"modules:\n"
        f"  - id: general\n"
        f"    kind: area\n"
        f"    name: General\n"
        f"  - id: project\n"
        f"    kind: area\n"
        f"    name: Project\n"
        f"\n"
        f"# Standard §10.4 — daemon self-update (architect.meshkore.com CDN).\n"
        f"# Set auto_update: false to require explicit confirmation per update.\n"
        f"daemon:\n"
        f"  auto_update: true\n"
        f"  auto_update_source: https://architect.meshkore.com/reference/cluster/scripts/daemon.py\n"
    )
    _w(paths.cluster_yaml, cluster_yaml)

    # ── public/README.md ────────────────────────────────────────────────
    _w(
        paths.public / "README.md",
        f"# {name}\n\n"
        f"This is a [MeshKore](https://meshkore.com/standard) cluster — a "
        f"local-first multi-agent project. Its entire state lives in this "
        f"repo's `.meshkore/` ledger; the project carries **no daemon code "
        f"of its own** — clone it anywhere and it stays portable.\n\n"
        f"One MeshKore daemon per machine serves every project on that "
        f"machine, routing each request to this cluster by its id "
        f"(`{slug}`), not by port. To work on this project, open the cockpit "
        f"at <https://architect.meshkore.com> and add it by its path — the "
        f"running daemon adopts it and the cockpit auto-detects it. If no "
        f"daemon is running on this machine yet, install MeshKore once (see "
        f"<https://meshkore.com/standard>) and it will serve this and all "
        f"your other clusters.\n",
    )

    # ── public/AGENT_INSTRUCTIONS.md + per-CLI render ───────────────────
    preamble = _fetch(_PREAMBLE_URL) or _fallback_preamble()
    instructions = (
        f"{_PREAMBLE_BEGIN}\n\n"
        f"{preamble.strip(chr(10))}\n\n"
        f"{_PREAMBLE_END}\n\n"
        f"{_OPERATOR_BEGIN}\n\n"
        f"# {name} — operator instructions\n\n"
        f"{desc}\n\n"
        f"Project-specific rules go here. This block is yours — the daemon "
        f"never touches it; it only manages the preamble above.\n\n"
        f"{_OPERATOR_END}\n"
    )
    src = paths.public / "AGENT_INSTRUCTIONS.md"
    _w(src, instructions)
    _render_cli_targets(paths, instructions, std_ver)

    # ── docs/ ───────────────────────────────────────────────────────────
    _w(
        paths.docs_dir / "governance.md",
        "# Governance\n\n"
        "This cluster follows the MeshKore standard. The canonical, "
        "authoritative spec lives at <https://meshkore.com/standard> "
        "(machine-readable: <https://api.meshkore.com/v1/standard.json>). "
        "Per standard R5 we link to it rather than copy it — read it there.\n",
    )
    _w(
        paths.docs_dir / "INDEX.md",
        "# docs/ — map\n\n"
        "- [governance.md](governance.md) — pointer to the MeshKore standard.\n",
    )

    # ── modules READMEs (Context tab reads these) ───────────────────────
    _w(
        paths.modules_dir / "general" / "README.md",
        "# general\n\n"
        "Catch-all area module for work that doesn't yet belong to a "
        "dedicated code module. Tasks live in `tasks/`; done tasks archive "
        "to `log/<YYYY-MM>/`.\n",
    )
    _w(
        paths.modules_dir / "project" / "README.md",
        "# project\n\n"
        "Cross-cutting meta area: deploy, docs, design, ops — work that "
        "spans the whole cluster rather than one code module.\n",
    )

    # ── starter task (schema 'task_frontmatter'; category == module) ────
    _w(
        paths.modules_dir / "general" / "tasks" / "T1-hello.md",
        f"---\n"
        f"id: T1\n"
        f"title: Hello, MeshKore\n"
        f"status: backlog\n"
        f"priority: medium\n"
        f"owner: unassigned\n"
        f"category: general\n"
        f"created: {today}\n"
        f"updated: {today}\n"
        f"---\n\n"
        f"Starter task — replace me. Describe the first real piece of work "
        f"for **{name}**.\n",
    )

    # ── team roster (initiative `agent-team`, ATM2) ─────────────────────
    # Seed the canonical 9-member default team into `.meshkore/team/` at init
    # so a fresh cluster is born with the roster. Idempotent + committed with
    # the repo (v27 git contract; no secrets). Boot re-seeds too (belt+braces).
    # TEG-1 — members seeded `exposure: external` (consultant) get their
    # bearer token minted into credentials/team-tokens.yaml (deny-listed).
    try:
        from team import TeamStore
        from teamext import TeamTokenStore

        _team = TeamStore(paths)
        _team.seed_defaults()
        TeamTokenStore(paths).ensure_for_external(_team)
    except Exception as e:  # noqa: BLE001 — seeding is best-effort at init
        _log(f"init: team seed skipped: {e}")

    # ── repo-root .gitignore (deny-list git contract) ───────────────────
    _write_gitignore(root)

    _log(
        f"init: scaffolded cluster '{slug}' ({name}) at standard v{std_ver} "
        f"under {paths.meshkore}"
    )
    return paths


def _render_cli_targets(paths: Paths, body: str, std_ver: int) -> None:
    """Mirror AGENT_INSTRUCTIONS.md into the §17 per-CLI files so they
    exist the moment init finishes (the daemon's renderer re-syncs them at
    every boot anyway). The two v19+ targets are written only when the
    cluster's standard version is ≥ 19."""
    for rel, audience in _CLI_TARGETS:
        if rel in (".cursor/rules/meshkore.mdc", ".clinerules") and std_ver < 19:
            continue
        header = (
            "<!-- Auto-rendered from .meshkore/public/AGENT_INSTRUCTIONS.md per\n"
            "     MeshKore standard §17 (v18+). Edit the source, not this file.\n"
            f"     Audience: {audience} -->\n\n"
        )
        dest = paths.root / rel
        try:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(header + body)
        except OSError as e:
            _log(f"init: render {rel} failed: {e}")


def _write_gitignore(root: Path) -> None:
    """Append the MeshKore runtime deny-list to the repo-root .gitignore
    (idempotent — skips lines already present). Git contract: commit
    public/ + docs/ + modules/ + roadmap/initiatives/; ignore runtime
    state, credentials, timeline, logs, queues, uploads, build artifacts."""
    block_header = "# MeshKore — runtime state (do not commit)"
    entries = [
        ".meshkore/.runtime/",
        ".meshkore/credentials/",
        ".meshkore/agents/",
        ".meshkore/timeline/",
        ".meshkore/log/",
        ".meshkore/queues/",
        ".meshkore/uploads/",
        ".meshkore/snapshots/",
        ".meshkore/state.json",
        ".meshkore/roadmap/state.json",
        ".meshkore/roadmap/state.js",
        # scripts/ holds the downloaded daemon (auto-updates → churns diffs
        # if committed) + the loopback TLS bundle (privkey is secret) — all
        # re-fetchable from /reference/cluster/scripts/, so never committed.
        ".meshkore/scripts/",
    ]
    gi = root / ".gitignore"
    existing = gi.read_text().splitlines() if gi.exists() else []
    have = set(line.strip() for line in existing)
    add = [e for e in entries if e not in have]
    if not add:
        return
    out = list(existing)
    if out and out[-1].strip() != "":
        out.append("")
    out.append(block_header)
    out.append(
        "# Everything else under .meshkore/ (public, docs, modules, "
        "roadmap/initiatives) IS versioned."
    )
    out.extend(add)
    gi.write_text("\n".join(out) + "\n")
