"""snapshots.py — Standard §20 (v19) pre-modification file snapshots.

DAH1 (initiative `daemon-audit-hardening`). The standard has mandated this
surface since v19 and every project's `CLAUDE.md` preamble tells every agent
that POSTing to it before editing an existing file is "non-negotiable" — but
the daemon had never implemented the route. `POST /snapshots` returned
`{"error": "unknown route"}`, so the operator's ability to inspect or restore
the pre-edit state between two commits did not exist. (The few folders under
`.meshkore/snapshots/` in this repo were all copied by hand.)

What a snapshot IS, per the standard: verbatim copies of the files an agent is
ABOUT to modify, plus a manifest describing who/why. It is deliberately not a
versioned filesystem (retention drops old buckets), not a git replacement (git
owns merged history), and not a transaction log (it captures the BEFORE state
only — the agent's write produces the AFTER, and git captures the result).

Layout, verbatim from the spec:

    .meshkore/snapshots/<YYYY-MM-DD>/<bucket-id>/_manifest.json
    .meshkore/snapshots/<YYYY-MM-DD>/<bucket-id>/files/<repo-relative-path>

`<bucket-id>` is `<YYYYMMDD>-<HHMMSSmmm>-<idHint>-<descSlug>-<4hex>`, which
sorts lexicographically into chronological order — that is what makes the
"newest first" listing a plain reverse-sort with no stat() calls.

Routes (ALL portal-token gated — scope_exclusions is explicit that snapshots
are never exposed to unauthenticated peers):

    POST   /snapshots                                    create
    GET    /snapshots?limit=N                            list buckets, newest first
    GET    /snapshots/<bucket>                           manifest
    GET    /snapshots/<bucket>/files/<repo-rel-path>     raw file body
    DELETE /snapshots/<bucket>                           operator cleanup

Config: `cluster.yaml#snapshots.{enabled,retention_days}` (true / 7).
Limits: 50 files per bucket, 5 MB per file — anything over is recorded in the
manifest as `skipped` rather than silently dropped, so a reader can tell "we
chose not to copy this" from "this was never mentioned".
"""

from __future__ import annotations

import hashlib
import os
import re
import secrets
import shutil
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional, Tuple

from fsatomic import atomic_write_json
from utils import _iso_now, _log

MAX_FILES_PER_BUCKET = 50
MAX_FILE_BYTES = 5_000_000
DEFAULT_RETENTION_DAYS = 7
LIST_LIMIT_DEFAULT = 200
LIST_LIMIT_MAX = 1000

_SLUG_RE = re.compile(r"[^a-z0-9]+")
# A bucket id is generated by us and then arrives back as a URL segment; pin
# its shape so `<bucket>` can never carry a path separator or `..`.
_BUCKET_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")


def _slug(text: str, *, fallback: str, maxlen: int = 24) -> str:
    out = _SLUG_RE.sub("-", (text or "").strip().lower()).strip("-")
    return out[:maxlen].strip("-") or fallback


def _bucket_id(
    now: datetime,
    *,
    id_hint: str,
    note: str,
) -> str:
    """`<YYYYMMDD>-<HHMMSSmmm>-<idHint>-<descSlug>-<4hex>`. Lexicographic
    order == chronological order, which is what makes listing cheap."""
    stamp = now.strftime("%Y%m%d-%H%M%S") + f"{now.microsecond // 1000:03d}"
    return "-".join(
        (
            stamp,
            _slug(id_hint, fallback="X", maxlen=16),
            _slug(note, fallback="snapshot", maxlen=32),
            secrets.token_hex(2),
        )
    )


class SnapshotsMixin:
    """Standard §20 handlers. Inherited by the Daemon, so `self.paths` /
    `self.cluster` / `self.hub` resolve per-request to the right
    ProjectContext exactly like every other per-project surface."""

    # ── config ──────────────────────────────────────────────────────────
    def _snapshots_config(self) -> Tuple[bool, int]:
        """`(enabled, retention_days)` from cluster.yaml, with the standard's
        defaults when the block is absent or malformed."""
        block = None
        try:
            data = self.cluster.data
            if isinstance(data, dict):
                block = data.get("snapshots")
        except Exception:  # noqa: BLE001 — a bad cluster.yaml must not break the route
            block = None
        if not isinstance(block, dict):
            return True, DEFAULT_RETENTION_DAYS
        enabled = block.get("enabled")
        try:
            days = int(block.get("retention_days") or DEFAULT_RETENTION_DAYS)
        except (TypeError, ValueError):
            days = DEFAULT_RETENTION_DAYS
        return (enabled is not False), max(1, min(365, days))

    # ── path helpers ────────────────────────────────────────────────────
    def _snapshot_bucket_dir(self, bucket: str) -> Optional[Any]:
        """Resolve `<bucket>` to its directory, or None when the id is
        malformed / unknown. The date folder is derived from the id's own
        prefix, so a caller can address a bucket without knowing its date."""
        if not _BUCKET_RE.match(bucket or ""):
            return None
        stamp = bucket[:8]
        if not stamp.isdigit():
            return None
        date = f"{stamp[:4]}-{stamp[4:6]}-{stamp[6:8]}"
        d = self.paths.snapshots_dir / date / bucket
        return d if d.is_dir() else None

    def _snapshot_gc(self, retention_days: int) -> List[str]:
        """Sweep date folders older than the retention window. Opportunistic
        (runs on create) — the write path keeps the tree bounded by
        definition, so §20 needs no separate cron."""
        removed: List[str] = []
        cutoff = (datetime.now(timezone.utc) - timedelta(days=retention_days)).strftime(
            "%Y-%m-%d"
        )
        root = self.paths.snapshots_dir
        if not root.is_dir():
            return removed
        for entry in sorted(root.iterdir()):
            if not entry.is_dir() or not re.match(r"^\d{4}-\d{2}-\d{2}$", entry.name):
                continue
            if entry.name >= cutoff:
                continue
            try:
                shutil.rmtree(entry)
                removed.append(entry.name)
            except OSError as e:
                _log(f"snapshots: GC could not remove {entry.name} ({e})")
        return removed

    # ── POST /snapshots ─────────────────────────────────────────────────
    def snapshot_create(self, body: Dict[str, Any]) -> Tuple[int, Dict[str, Any]]:
        enabled, retention_days = self._snapshots_config()
        if not enabled:
            return 403, {
                "error": "snapshots_disabled",
                "hint": "set cluster.yaml snapshots.enabled: true",
            }
        if not isinstance(body, dict):
            return 400, {"error": "JSON object body required"}
        raw_paths = body.get("paths")
        if not isinstance(raw_paths, list) or not raw_paths:
            return 400, {"error": "paths must be a non-empty array of strings"}

        root = self.paths.root.resolve()
        now = datetime.now(timezone.utc)
        warnings: List[str] = []
        files: List[Dict[str, Any]] = []

        wanted = [str(p).strip() for p in raw_paths if str(p or "").strip()]
        if len(wanted) > MAX_FILES_PER_BUCKET:
            warnings.append(
                f"{len(wanted)} paths requested; only the first "
                f"{MAX_FILES_PER_BUCKET} were snapshotted (per-bucket limit)"
            )
            wanted = wanted[:MAX_FILES_PER_BUCKET]

        note = str(body.get("note") or "").strip()[:240]
        id_hint = str(
            body.get("agent_id")
            or body.get("initiative_id")
            or body.get("task_id")
            or "X"
        )
        bucket = _bucket_id(
            now, id_hint=id_hint, note=note or str(body.get("task_id") or "")
        )
        date = now.strftime("%Y-%m-%d")
        bucket_dir = self.paths.snapshots_dir / date / bucket
        files_dir = bucket_dir / "files"

        for rel in wanted:
            # Every path is interpreted repo-relative; anything that escapes
            # the project root is refused, not clamped.
            if rel.startswith("/") or ".." in rel.split("/"):
                files.append({"path": rel, "skipped": "path traversal"})
                continue
            src = (root / rel).resolve()
            try:
                src.relative_to(root)
            except ValueError:
                files.append({"path": rel, "skipped": "outside project root"})
                continue
            if not src.is_file():
                # Newly-created files are EXEMPT per the agent contract, so
                # this is an expected outcome, not an error.
                files.append({"path": rel, "skipped": "not an existing file"})
                continue
            try:
                size = src.stat().st_size
            except OSError as e:
                files.append({"path": rel, "skipped": f"stat failed: {e}"})
                continue
            if size > MAX_FILE_BYTES:
                files.append(
                    {
                        "path": rel,
                        "size": size,
                        "skipped": f"over {MAX_FILE_BYTES} bytes",
                    }
                )
                continue
            dest = files_dir / rel
            try:
                dest.parent.mkdir(parents=True, exist_ok=True)
                data = src.read_bytes()
                dest.write_bytes(data)
            except OSError as e:
                files.append({"path": rel, "skipped": f"copy failed: {e}"})
                continue
            files.append(
                {
                    "path": rel,
                    "size": size,
                    "sha256": hashlib.sha256(data).hexdigest(),
                }
            )

        copied = [f for f in files if "skipped" not in f]
        if not copied and not files_dir.exists():
            # Nothing was copied — don't leave an empty bucket on disk, but
            # still tell the caller precisely why each path was skipped.
            return 200, {
                "id": None,
                "created": False,
                "files": files,
                "warnings": warnings + ["no existing files to snapshot"],
            }

        manifest = {
            "id": bucket,
            "date": date,
            "created_at": _iso_now(),
            "conv": str(body.get("conv") or "") or None,
            "agent_id": str(body.get("agent_id") or "") or None,
            "agent_type": str(body.get("agent_type") or "") or None,
            "initiative_id": str(body.get("initiative_id") or "") or None,
            "task_id": str(body.get("task_id") or "") or None,
            "msg_id": str(body.get("msg_id") or "") or None,
            "note": note or None,
            "files": files,
            "warnings": warnings,
        }
        try:
            bucket_dir.mkdir(parents=True, exist_ok=True)
            atomic_write_json(bucket_dir / "_manifest.json", manifest, sort_keys=True)
        except OSError as e:
            return 500, {"error": f"could not write manifest: {e}"}

        self._snapshot_daily_log(manifest)
        gc_removed = self._snapshot_gc(retention_days)
        if gc_removed:
            _log(f"snapshots: GC removed {len(gc_removed)} expired day(s)")
        try:
            if getattr(self, "hub", None) is not None:
                self.hub.broadcast(
                    {
                        "type": "snapshot.created",
                        "id": bucket,
                        "conv": manifest["conv"],
                        "agent_id": manifest["agent_id"],
                        "files": [f["path"] for f in copied],
                        "ts": manifest["created_at"],
                    }
                )
        except Exception as e:  # noqa: BLE001 — broadcast failure is non-fatal
            _log(f"snapshots: broadcast failed: {e}")
        return 201, {
            "id": bucket,
            "created": True,
            "date": date,
            "files": files,
            "warnings": warnings,
        }

    def _snapshot_daily_log(self, manifest: Dict[str, Any]) -> None:
        """Append the §6 daily-log entry the standard's
        `daily_log_integration` calls for. Best-effort: a snapshot that
        copied fine must not fail because the diary is unwritable."""
        try:
            copied = [f for f in manifest["files"] if "skipped" not in f]
            if not copied:
                return
            day = manifest["date"]
            hhmmss = str(manifest["created_at"])[11:19] or "00:00:00"
            who = manifest.get("agent_id") or manifest.get("agent_type") or "agent"
            lines = [
                f"\n## {hhmmss} · snapshot {manifest['id']}\n",
                f"- agent: `{who}`"
                + (f" · conv `{manifest['conv']}`" if manifest.get("conv") else "")
                + (
                    f" · task `{manifest['task_id']}`"
                    if manifest.get("task_id")
                    else ""
                )
                + "\n",
            ]
            if manifest.get("note"):
                lines.append(f"- note: {manifest['note']}\n")
            for f in copied:
                lines.append(f"  - `{f['path']}` ({f['size']} B)\n")
            lines.append(f"- restore: `GET /snapshots/{manifest['id']}/files/<path>`\n")
            log_file = self.paths.log_dir / f"{day}.md"
            log_file.parent.mkdir(parents=True, exist_ok=True)
            # Append-only, per §6 — never rewrite a past entry.
            with open(log_file, "a", encoding="utf-8") as fh:
                fh.write("".join(lines))
        except Exception as e:  # noqa: BLE001
            _log(f"snapshots: daily-log append failed: {e}")

    # ── GET /snapshots ──────────────────────────────────────────────────
    def snapshot_list(
        self, limit: int = LIST_LIMIT_DEFAULT
    ) -> Tuple[int, Dict[str, Any]]:
        limit = max(1, min(LIST_LIMIT_MAX, int(limit or LIST_LIMIT_DEFAULT)))
        root = self.paths.snapshots_dir
        out: List[Dict[str, Any]] = []
        if not root.is_dir():
            return 200, {"buckets": [], "generated_at": _iso_now()}
        # Bucket ids sort chronologically, so newest-first is a reverse walk
        # of the date dirs and then of the buckets inside — no stat() needed.
        for date_dir in sorted(root.iterdir(), reverse=True):
            if not date_dir.is_dir():
                continue
            for bucket_dir in sorted(date_dir.iterdir(), reverse=True):
                if len(out) >= limit:
                    return 200, {"buckets": out, "generated_at": _iso_now()}
                manifest = bucket_dir / "_manifest.json"
                if not manifest.is_file():
                    continue
                try:
                    import json as _json

                    m = _json.loads(manifest.read_text(encoding="utf-8"))
                except Exception:  # noqa: BLE001 — a corrupt bucket is skipped, not fatal
                    continue
                out.append(
                    {
                        "id": m.get("id") or bucket_dir.name,
                        "date": m.get("date") or date_dir.name,
                        "created_at": m.get("created_at"),
                        "conv": m.get("conv"),
                        "agent_id": m.get("agent_id"),
                        "task_id": m.get("task_id"),
                        "note": m.get("note"),
                        "file_count": len(
                            [f for f in (m.get("files") or []) if "skipped" not in f]
                        ),
                    }
                )
        return 200, {"buckets": out, "generated_at": _iso_now()}

    # ── GET /snapshots/<bucket> ─────────────────────────────────────────
    def snapshot_manifest(self, bucket: str) -> Tuple[int, Dict[str, Any]]:
        d = self._snapshot_bucket_dir(bucket)
        if d is None:
            return 404, {"error": "unknown snapshot bucket", "id": bucket}
        try:
            import json as _json

            return 200, _json.loads((d / "_manifest.json").read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001
            return 500, {"error": f"manifest unreadable: {e}", "id": bucket}

    # ── GET /snapshots/<bucket>/files/<path> ────────────────────────────
    def snapshot_file_path(self, bucket: str, rel: str) -> Optional[Any]:
        """Resolved on-disk path of one snapshotted file, or None. Confined
        to the bucket's `files/` dir — the caller serves the bytes."""
        d = self._snapshot_bucket_dir(bucket)
        if d is None:
            return None
        files_root = (d / "files").resolve()
        try:
            target = (files_root / rel).resolve()
            target.relative_to(files_root)  # raises if the path escaped
        except (ValueError, OSError):
            return None
        return target if target.is_file() else None

    # ── DELETE /snapshots/<bucket> ──────────────────────────────────────
    def snapshot_delete(self, bucket: str) -> Tuple[int, Dict[str, Any]]:
        d = self._snapshot_bucket_dir(bucket)
        if d is None:
            return 404, {"error": "unknown snapshot bucket", "id": bucket}
        try:
            shutil.rmtree(d)
        except OSError as e:
            return 500, {"error": f"could not remove bucket: {e}", "id": bucket}
        try:
            # Drop the date folder too once it holds nothing.
            if not any(d.parent.iterdir()):
                os.rmdir(d.parent)
        except OSError:
            pass
        try:
            if getattr(self, "hub", None) is not None:
                self.hub.broadcast(
                    {"type": "snapshot.removed", "id": bucket, "ts": _iso_now()}
                )
        except Exception as e:  # noqa: BLE001
            _log(f"snapshots: broadcast failed: {e}")
        return 200, {"deleted": True, "id": bucket}
