/**
 * `meshcore agent create` and `meshcore agent list`.
 */
import path from 'node:path';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import readline from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import chalk from 'chalk';

interface AgentCreateOptions {
  client: 'claude-code' | 'deepseek' | 'qwen' | 'cursor' | 'custom';
  identity: string;
  role?: string;
  noPrompt?: boolean;
}

const ENV_VARS: Record<string, string[]> = {
  'claude-code': ['ANTHROPIC_API_KEY'],
  'deepseek':    ['DEEPSEEK_API_KEY'],
  'qwen':        ['DASHSCOPE_API_KEY'],
  'cursor':      [], // uses local Cursor CLI auth
  'custom':      [],
};

export const agentCmd = {
  async create(opts: AgentCreateOptions): Promise<void> {
    const meshkoreDir = path.resolve('.meshkore');
    if (!existsSync(meshkoreDir)) throw new Error('.meshkore/ not found');

    if (!opts.client) throw new Error('--client is required');
    if (!opts.identity) throw new Error('--identity is required');

    const agentsDir = path.join(meshkoreDir, 'agents');
    const credsDir = path.join(meshkoreDir, 'credentials');
    mkdirSync(agentsDir, { recursive: true });
    mkdirSync(credsDir, { recursive: true });

    const yamlPath = path.join(agentsDir, `${opts.identity}.yaml`);
    if (existsSync(yamlPath)) throw new Error(`agent ${opts.identity} already exists`);

    // Credentials: prompt for each env var the client expects
    const credsFile = path.join(credsDir, `${opts.client}.env`);
    const requiredEnv = ENV_VARS[opts.client] ?? [];
    if (requiredEnv.length && !opts.noPrompt) {
      const rl = readline.createInterface({ input: stdin, output: stdout });
      let lines = existsSync(credsFile) ? readFileSync(credsFile, 'utf8') : '';
      for (const v of requiredEnv) {
        if (lines.includes(v + '=')) continue;
        const val = (await rl.question(`${v} (will be stored in ${credsFile}): `)).trim();
        if (val) lines += `${v}=${val}\n`;
      }
      rl.close();
      writeFileSync(credsFile, lines, { mode: 0o600 });
    }

    const yaml = `# .meshkore/agents/${opts.identity}.yaml — generated by \`meshcore agent create\`
identity: ${opts.identity}
role: agent
client: ${opts.client}
agent_role: ${opts.role || 'developer'}
${requiredEnv.length ? `credentials: credentials/${opts.client}.env` : '# credentials: none'}
permissions:
  edit: true
  shell: true
  network: restricted
`;
    writeFileSync(yamlPath, yaml);

    console.log(`\n  ✓ agent created`);
    console.log(`    file:       ${path.relative(process.cwd(), yamlPath)}`);
    console.log(`    identity:   ${opts.identity}`);
    console.log(`    client:     ${opts.client}`);
    if (requiredEnv.length) {
      console.log(`    creds:      ${path.relative(process.cwd(), credsFile)}`);
    }
    console.log(`\n    Run with:   meshcore start --identity ${opts.identity}\n`);
  },

  async list(): Promise<void> {
    const agentsDir = path.resolve('.meshkore', 'agents');
    if (!existsSync(agentsDir)) {
      console.log('No agents declared yet.');
      return;
    }
    const files = readdirSync(agentsDir).filter(f => f.endsWith('.yaml'));
    if (!files.length) {
      console.log('No agents declared yet.');
      return;
    }
    console.log(`\n  ${files.length} agent(s)\n`);
    for (const f of files) {
      const text = readFileSync(path.join(agentsDir, f), 'utf8');
      const id = /^identity:\s*(\S+)/m.exec(text)?.[1] ?? f;
      const client = /^client:\s*(\S+)/m.exec(text)?.[1] ?? '?';
      const role = /^agent_role:\s*(\S+)/m.exec(text)?.[1] ?? '-';
      console.log(`  ${chalk.cyan(id.padEnd(28))} ${chalk.gray(client.padEnd(14))} ${role}`);
    }
    console.log();
  },
};
