/**
 * `meshcore agent create` and `meshcore agent list`.
 */
import path from 'node:path';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs';
import readline from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import chalk from 'chalk';

interface AgentCreateOptions {
  client: 'claude-code' | 'deepseek' | 'qwen' | 'cursor' | 'custom';
  identity: string;
  role?: string;
  noPrompt?: boolean;
}

const ENV_VARS: Record<string, string[]> = {
  'claude-code': ['ANTHROPIC_API_KEY'],
  'codex':       ['OPENAI_API_KEY'],
  'deepseek':    ['DEEPSEEK_API_KEY'],
  'qwen':        ['DASHSCOPE_API_KEY'],
  'cursor':      ['CURSOR_API_KEY'],   // optional — Cursor CLI may also do its own browser OAuth
  'custom':      [],
};

/**
 * Create an agent identity programmatically (used by HTTP `POST /agents`).
 * Throws on duplicate identity, missing client, etc.
 *
 *   credentialValue = the secret to write into the env file (one entry,
 *   keyed by the client's first ENV_VAR). When falsy, the env file is
 *   touched but left empty so the user can fill it in later.
 */
export function createAgentIdentity(opts: {
  meshkoreDir: string;
  identity: string;
  client: string;
  agentRole?: string;
  credentialValue?: string;
}): { yamlPath: string; credsPath: string | null } {
  if (!opts.client) throw new Error('client is required');
  if (!opts.identity) throw new Error('identity is required');
  if (!/^[a-z0-9][a-z0-9-]{1,40}$/.test(opts.identity)) {
    throw new Error('identity must be lowercase, 2-41 chars, [a-z0-9-]');
  }
  if (!ENV_VARS.hasOwnProperty(opts.client)) {
    throw new Error(`unknown client '${opts.client}' (allowed: ${Object.keys(ENV_VARS).join(', ')})`);
  }
  const agentsDir = path.join(opts.meshkoreDir, 'agents');
  const credsDir  = path.join(opts.meshkoreDir, 'credentials');
  mkdirSync(agentsDir, { recursive: true });
  mkdirSync(credsDir,  { recursive: true });

  const yamlPath = path.join(agentsDir, `${opts.identity}.yaml`);
  if (existsSync(yamlPath)) throw new Error(`agent ${opts.identity} already exists`);

  const requiredEnv = ENV_VARS[opts.client] ?? [];
  let credsPath: string | null = null;
  if (requiredEnv.length) {
    credsPath = path.join(credsDir, `${opts.client}.env`);
    let lines = existsSync(credsPath) ? readFileSync(credsPath, 'utf8') : '';
    if (opts.credentialValue) {
      const key = requiredEnv[0]!;
      if (!lines.includes(key + '=')) {
        lines += `${key}=${opts.credentialValue}\n`;
      }
    }
    writeFileSync(credsPath, lines, { mode: 0o600 });
  }

  const yaml = `# .meshkore/agents/${opts.identity}.yaml — generated by \`meshcore agent create\`
identity: ${opts.identity}
role: agent
client: ${opts.client}
agent_role: ${opts.agentRole || 'developer'}
${requiredEnv.length ? `credentials: credentials/${opts.client}.env` : '# credentials: none'}
permissions:
  edit: true
  shell: true
  network: restricted
`;
  writeFileSync(yamlPath, yaml);
  return { yamlPath, credsPath };
}

export const agentCmd = {
  async create(opts: AgentCreateOptions): Promise<void> {
    const meshkoreDir = path.resolve('.meshkore');
    if (!existsSync(meshkoreDir)) throw new Error('.meshkore/ not found');

    if (!opts.client) throw new Error('--client is required');
    if (!opts.identity) throw new Error('--identity is required');

    // Optional interactive credential prompt (CLI only — HTTP path passes
    // the token directly through createAgentIdentity).
    let credentialValue: string | undefined;
    const requiredEnv = ENV_VARS[opts.client] ?? [];
    if (requiredEnv.length && !opts.noPrompt) {
      const rl = readline.createInterface({ input: stdin, output: stdout });
      const credsDir = path.join(meshkoreDir, 'credentials');
      const credsFile = path.join(credsDir, `${opts.client}.env`);
      const existing = existsSync(credsFile) ? readFileSync(credsFile, 'utf8') : '';
      const key = requiredEnv[0]!;
      if (!existing.includes(key + '=')) {
        const val = (await rl.question(`${key} (will be stored in ${credsFile}): `)).trim();
        if (val) credentialValue = val;
      }
      rl.close();
    }

    const { yamlPath, credsPath } = createAgentIdentity({
      meshkoreDir,
      identity: opts.identity,
      client: opts.client,
      agentRole: opts.role,
      credentialValue,
    });

    console.log(`\n  ✓ agent created`);
    console.log(`    file:       ${path.relative(process.cwd(), yamlPath)}`);
    console.log(`    identity:   ${opts.identity}`);
    console.log(`    client:     ${opts.client}`);
    if (credsPath) console.log(`    creds:      ${path.relative(process.cwd(), credsPath)}`);
    console.log(`\n    Run with:   meshcore start --identity ${opts.identity}\n`);
  },

  async list(): Promise<void> {
    const agentsDir = path.resolve('.meshkore', 'agents');
    if (!existsSync(agentsDir)) {
      console.log('No agents declared yet.');
      return;
    }
    const files = readdirSync(agentsDir).filter(f => f.endsWith('.yaml'));
    if (!files.length) {
      console.log('No agents declared yet.');
      return;
    }
    console.log(`\n  ${files.length} agent(s)\n`);
    for (const f of files) {
      const text = readFileSync(path.join(agentsDir, f), 'utf8');
      const id = /^identity:\s*(\S+)/m.exec(text)?.[1] ?? f;
      const client = /^client:\s*(\S+)/m.exec(text)?.[1] ?? '?';
      const role = /^agent_role:\s*(\S+)/m.exec(text)?.[1] ?? '-';
      console.log(`  ${chalk.cyan(id.padEnd(28))} ${chalk.gray(client.padEnd(14))} ${role}`);
    }
    console.log();
  },
};
